### ISSUE TITLE
Playground doesn't accept triple bacticks

### ISSUE THREAD

**Issue by arthurdenner** [Lalit2005/hyperdocs#6]
```
Hi, I'm a block with triple backticks :)
```

The snippet above doesn't work on the playground, it results in a black text in a black background:

![image](https://user-images.githubusercontent.com/13774309/171453910-1b9202a8-1600-40a5-8e41-1c01a2909b5c.png)

**Comment by Lalit2005** [comment]
Thanks for pointing this out @arthurdenner :D

The problem was with the `rehype-highlighter` package in the [repl](https://replit.com/@lalitcodes/hyperdocs-playground#index.mjs). It's now fixed 🎉 

![image](https://user-images.githubusercontent.com/69138026/172040028-bd836c0a-0c23-4d1b-a839-06eae8b2793f.png)
